---
- name: show ng-info file name
  hosts: ngate1
  tasks:
    - name: capture ng-info result file name
      shell: >
        /opt/ngate/sbin/ng-info | grep 'Resulting archive' | awk '{print $4}'
      register: ng_info
    - set_fact: ng_info_file={{ ng_info.stdout }}
    - name: get ng-info
      ansible.builtin.fetch:
        src: "{{ ng_info_file }}"
        dest: /tmp/
