---
- name: show ng-info file name
  hosts: ngate1
  tasks:
    - name: capture ng-info result file name
      command: "/opt/ngate/sbin/ng-info | grep 'Resulting archive' | awk '{print $4}'"
      register: ng_info_file
    - debug: var=ng_info_file
